export default {
  ttl: 'International Fixed Calendar',
  t_in: 'Date to convert', t_yr: 'Full year',
  s1: 'Sol: Jun–Jul', s2: 'Sol: Jul–Aug',
  t_pk: 'Calendar', t_res: 'Result', t_hl: 'International holidays of the year',
  t_diff: 'Difference between dates',
  cg: 'Gregorian', cj: 'Julian', cc: 'Chinese', ch: 'Hebrew',
  ci: 'Hindu', cm: 'Islamic', cp: 'Persian', ck: 'Coptic',
  go: 'Convert', bad: 'This date does not exist in the chosen calendar',
  badyear: 'Year must be between 1 and 9999', badseason: 'Season 1–24, day 1–15',
  copy: 'Copy', share: 'Share', ics: 'ICS',
  copied: 'Copied', copyFail: 'Copy failed', linkCopied: 'Link copied',
  icsDone: 'ICS file downloaded',
  dDiff: 'Total', dDays: 'days', dWeeks: 'weeks', dYMD: 'Calendar',
  dYears: 'y.', dMonths: 'mo.', dIFC: 'By IFC',
  m: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  mg: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  im: ['January','February','March','April','May','June','Sol','July','August','September','October','November','December'],
  img: ['January','February','March','April','May','June','Sol','July','August','September','October','November','December'],
  wd: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
  ws: ['Su','Mo','Tu','We','Th','Fr','Sa'], pw: ['Mo','Tu','We','Th','Fr','Sa','Su'],
  leap: 'Leap Day', year: 'Year Day', noweek: 'outside the week',
  gr:'Gregorian', ju:'Julian', cn:'Chinese', hb:'Hebrew', in:'Hindu', is:'Islamic', pe:'Persian', co:'Coptic',
  legend: '● — holiday. Every month starts on Sunday; hover a day to see its Gregorian date.',
  note: 'All dates via JDN. Hindu (Vikram Samvat) — simplified model. Islamic, Persian, Coptic — tabular algorithms.',
  hm:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhirah','Rajab','Shaaban','Ramadan','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  isml:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhirah','Rajab','Shaaban','Ramadan','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  pm:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:"New Year's Day", orx:'Christmas (Orthodox)', lang:'Mother Language Day', w:"Women's Day",
    water:'World Water Day', earth:'Earth Day', lab:'Labour Day', env:'Environment Day',
    ch:"Children's Day", youth:'Youth Day', peace:'Day of Peace', teach:"Teachers' Day",
    un:'United Nations Day', hr:'Human Rights Day', xm:'Christmas (Western)', ev:"New Year's Eve",
    ew:'Easter (Western)', eo:'Easter (Orthodox)', val:"Valentine's Day",
    father:"Father's Day", mother:"Mother's Day", men:"International Men's Day", book:'World Book Day',
    health:'World Health Day', space:'Human Space Flight Day', music:'International Music Day',
    disab:'Day of Persons with Disabilities', vol:'Volunteer Day', vdayE:'Victory Day (East)',
    vdayW:'Victory Day (West)', holocaust:'Holocaust Remembrance Day', oceans:'World Oceans Day',
    elderly:'Day of Older Persons', post:'World Post Day', tv:'World Television Day',
    mountains:'International Mountain Day', migrants:'International Migrants Day',
    peace2:'Day of Peace and Reconciliation', diwali:'Diwali', holi:'Holi',
    eidF:'Eid al-Fitr', eidA:'Eid al-Adha'
  },
  tl:'Dark theme', tn:'Light theme', lb:'Language'
};