export default {
  ttl: 'Calendario Fijo Internacional',
  t_in: 'Fecha a convertir', t_yr: 'Año completo',
  s1: 'Sol: jun–jul', s2: 'Sol: jul–ago',
  t_pk: 'Calendario', t_res: 'Resultado', t_hl: 'Días festivos internacionales del año',
  t_diff: 'Diferencia entre fechas',
  cg:'Gregoriano', cj:'Juliano', cc:'Chino', ch:'Hebreo',
  ci:'Hindú', cm:'Islámico', cp:'Persa', ck:'Copto',
  go:'Convertir', bad:'Esta fecha no existe en el calendario elegido',
  badyear:'El año debe estar entre 1 y 9999', badseason:'Estación 1–24, día 1–15',
  copy:'Copiar', share:'Compartir', ics:'ICS',
  copied:'Copiado', copyFail:'Error al copiar', linkCopied:'Enlace copiado',
  icsDone:'Archivo ICS descargado',
  dDiff:'Total', dDays:'días', dWeeks:'sem.', dYMD:'Calendario',
  dYears:'a.', dMonths:'meses', dIFC:'Por CFI',
  m:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
  mg:['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
  im:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Sol','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
  img:['enero','febrero','marzo','abril','mayo','junio','Sol','julio','agosto','septiembre','octubre','noviembre','diciembre'],
  wd:['domingo','lunes','martes','miércoles','jueves','viernes','sábado'],
  ws:['Do','Lu','Ma','Mi','Ju','Vi','Sá'], pw:['Lu','Ma','Mi','Ju','Vi','Sá','Do'],
  leap:'Día Bisiesto', year:'Día del Año', noweek:'fuera de la semana',
  gr:'Gregoriano', ju:'Juliano', cn:'Chino', hb:'Hebreo',
  in:'Hindú', is:'Islámico', pe:'Persa', co:'Copto',
  legend:'● — festivo. Cada mes comienza en domingo; pasa el cursor sobre un día para ver su fecha gregoriana.',
  note:'Todas las fechas vía JDN. Hindú (Vikram Samvat) — modelo simplificado. Islámico, Persa, Copto — algoritmos tabulares.',
  hm:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadán','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  isml:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadán','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  pm:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Año Nuevo', orx:'Navidad (Ortodoxa)', lang:'Día de la Lengua Materna', w:'Día de la Mujer',
    water:'Día Mundial del Agua', earth:'Día de la Tierra', lab:'Día del Trabajo', env:'Día del Medio Ambiente',
    ch:'Día del Niño', youth:'Día de la Juventud', peace:'Día de la Paz', teach:'Día del Maestro',
    un:'Día de las Naciones Unidas', hr:'Día de los Derechos Humanos', xm:'Navidad (Occidental)', ev:'Nochevieja',
    ew:'Pascua (Occidental)', eo:'Pascua (Ortodoxa)', val:'Día de San Valentín',
    father:'Día del Padre', mother:'Día de la Madre', men:'Día Internacional del Hombre', book:'Día Mundial del Libro',
    health:'Día Mundial de la Salud', space:'Día del Vuelo Espacial Humano', music:'Día Internacional de la Música',
    disab:'Día de las Personas con Discapacidad', vol:'Día del Voluntario', vdayE:'Día de la Victoria (Este)',
    vdayW:'Día de la Victoria (Oeste)', holocaust:'Día de la Memoria del Holocausto', oceans:'Día Mundial de los Océanos',
    elderly:'Día Internacional de las Personas Mayores', post:'Día Mundial del Correo', tv:'Día Mundial de la Televisión',
    mountains:'Día Internacional de las Montañas', migrants:'Día Internacional del Migrante',
    peace2:'Día de la Paz y Reconciliación', diwali:'Diwali', holi:'Holi',
    eidF:'Eid al-Fitr', eidA:'Eid al-Adha'
  },
  tl:'Tema oscuro', tn:'Tema claro', lb:'Idioma'
};