export default {
  ttl: 'Calendrier Fixe International',
  t_in: 'Date à convertir', t_yr: 'Année complète',
  s1: 'Sol: juin–juil', s2: 'Sol: juil–août',
  t_pk: 'Calendrier', t_res: 'Résultat', t_hl: 'Jours fériés internationaux de l\'année',
  t_diff: 'Différence entre les dates',
  cg:'Grégorien', cj:'Julien', cc:'Chinois', ch:'Hébreu',
  ci:'Hindou', cm:'Islamique', cp:'Persan', ck:'Copte',
  go:'Convertir', bad:'Cette date n\'existe pas dans le calendrier choisi',
  badyear:'L\'année doit être comprise entre 1 et 9999', badseason:'Saison 1–24, jour 1–15',
  copy:'Copier', share:'Partager', ics:'ICS',
  copied:'Copié', copyFail:'Échec de la copie', linkCopied:'Lien copié',
  icsDone:'Fichier ICS téléchargé',
  dDiff:'Total', dDays:'jours', dWeeks:'sem.', dYMD:'Calendaire',
  dYears:'a.', dMonths:'m.', dIFC:'Par CFI',
  m:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  mg:['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],
  im:['Janvier','Février','Mars','Avril','Mai','Juin','Sol','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  img:['janvier','février','mars','avril','mai','juin','Sol','juillet','août','septembre','octobre','novembre','décembre'],
  wd:['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'],
  ws:['Di','Lu','Ma','Me','Je','Ve','Sa'], pw:['Lu','Ma','Me','Je','Ve','Sa','Di'],
  leap:'Jour Bissextile', year:'Jour de l\'Année', noweek:'hors semaine',
  gr:'Grégorien', ju:'Julien', cn:'Chinois', hb:'Hébreu',
  in:'Hindou', is:'Islamique', pe:'Persan', co:'Copte',
  legend:'● — jour férié. Chaque mois commence un dimanche ; survolez un jour pour voir sa date grégorienne.',
  note:'Toutes les dates via JDN. Hindou (Vikram Samvat) — modèle simplifié. Islamique, Persan, Copte — algorithmes tabulaires.',
  hm:['Tichri','Hechvan','Kislev','Tevet','Chevat','Adar','Nissan','Iyar','Sivan','Tamouz','Av','Eloul','Adar II'],
  hml:['Tichri','Hechvan','Kislev','Tevet','Chevat','Adar','Nissan','Iyar','Sivan','Tamouz','Av','Eloul','Adar II'],
  im2:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  ism:['Mouharram','Safar','Rabi al-awwal','Rabi al-thani','Joumada al-oula','Joumada al-akhira','Rajab','Chaabane','Ramadan','Chawwal','Dhou al-Qada','Dhou al-Hijja'],
  isml:['Mouharram','Safar','Rabi al-awwal','Rabi al-thani','Joumada al-oula','Joumada al-akhira','Rajab','Chaabane','Ramadan','Chawwal','Dhou al-Qada','Dhou al-Hijja'],
  pm:['Farwardin','Ordibehecht','Khordad','Tir','Mordad','Chahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farwardin','Ordibehecht','Khordad','Tir','Mordad','Chahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Mechir','Paremhat','Parmouti','Pachons','Paoni','Epip','Mesori','Épagoménal'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Mechir','Paremhat','Parmouti','Pachons','Paoni','Epip','Mesori','Épagoménal'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Jour de l\'An', orx:'Noël (Orthodoxe)', lang:'Journée de la Langue Maternelle', w:'Journée de la Femme',
    water:'Journée Mondiale de l\'Eau', earth:'Jour de la Terre', lab:'Fête du Travail', env:'Journée de l\'Environnement',
    ch:'Journée de l\'Enfance', youth:'Journée de la Jeunesse', peace:'Journée de la Paix', teach:'Journée des Enseignants',
    un:'Journée de l\'ONU', hr:'Journée des Droits de l\'Homme', xm:'Noël (Occidental)', ev:'Saint-Sylvestre',
    ew:'Pâques (Occidentale)', eo:'Pâques (Orthodoxe)', val:'Saint-Valentin',
    father:'Fête des Pères', mother:'Fête des Mères', men:'Journée Internationale de l\'Homme', book:'Journée Mondiale du Livre',
    health:'Journée Mondiale de la Santé', space:'Journée du Vol Spatial Habité', music:'Journée Internationale de la Musique',
    disab:'Journée des Personnes Handicapées', vol:'Journée du Bénévolat', vdayE:'Jour de la Victoire (Est)',
    vdayW:'Jour de la Victoire (Ouest)', holocaust:'Journée de la Shoah', oceans:'Journée Mondiale des Océans',
    elderly:'Journée des Personnes Âgées', post:'Journée Mondiale de la Poste', tv:'Journée Mondiale de la Télévision',
    mountains:'Journée Internationale de la Montagne', migrants:'Journée Internationale des Migrants',
    peace2:'Journée de la Paix et de la Réconciliation', diwali:'Diwali', holi:'Holi',
    eidF:'Aïd al-Fitr', eidA:'Aïd al-Adha'
  },
  tl:'Thème sombre', tn:'Thème clair', lb:'Langue'
};