export default {
  ttl: 'Kalender Tetap Internasional',
  t_in: 'Tanggal untuk dikonversi', t_yr: 'Tahun penuh',
  s1: 'Sol: Jun–Jul', s2: 'Sol: Jul–Agu',
  t_pk: 'Kalender', t_res: 'Hasil', t_hl: 'Hari libur internasional tahun ini',
  t_diff: 'Selisih antara tanggal',
  cg:'Gregorian', cj:'Julian', cc:'Tionghoa', ch:'Ibrani',
  ci:'Hindu', cm:'Islam', cp:'Persia', ck:'Koptik',
  go:'Konversi', bad:'Tanggal ini tidak ada di kalender yang dipilih',
  badyear:'Tahun harus antara 1 dan 9999', badseason:'Musim 1–24, hari 1–15',
  copy:'Salin', share:'Bagikan', ics:'ICS',
  copied:'Disalin', copyFail:'Gagal menyalin', linkCopied:'Tautan disalin',
  icsDone:'File ICS diunduh',
  dDiff:'Total', dDays:'hari', dWeeks:'mgg.', dYMD:'Kalender',
  dYears:'th.', dMonths:'bln', dIFC:'Per KTI',
  m:['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],
  mg:['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],
  im:['Januari','Februari','Maret','April','Mei','Juni','Sol','Juli','Agustus','September','Oktober','November','Desember'],
  img:['Januari','Februari','Maret','April','Mei','Juni','Sol','Juli','Agustus','September','Oktober','November','Desember'],
  wd:['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'],
  ws:['Mg','Sn','Sl','Rb','Km','Jm','Sb'], pw:['Sn','Sl','Rb','Km','Jm','Sb','Mg'],
  leap:'Hari Kabisat', year:'Hari Tahun', noweek:'di luar minggu',
  gr:'Gregorian', ju:'Julian', cn:'Tionghoa', hb:'Ibrani',
  in:'Hindu', is:'Islam', pe:'Persia', co:'Koptik',
  legend:'● — hari libur. Setiap bulan dimulai pada hari Minggu; arahkan kursor ke hari untuk melihat tanggal Gregorian.',
  note:'Semua tanggal melalui JDN. Hindu (Vikram Samvat) — model yang disederhanakan. Islam, Persia, Koptik — algoritma tabel.',
  hm:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Chaitra','Waisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Asywin','Kartika','Margasirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Waisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Asywin','Kartika','Margasirsha','Pausha','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabiul Awal','Rabiul Akhir','Jumadil Awal','Jumadil Akhir','Rajab','Syaban','Ramadan','Syawal','Zulkaidah','Zulhijah'],
  isml:['Muharram','Safar','Rabiul Awal','Rabiul Akhir','Jumadil Awal','Jumadil Akhir','Rajab','Syaban','Ramadan','Syawal','Zulkaidah','Zulhijah'],
  pm:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farvardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Tahun Baru', orx:'Natal (Ortodoks)', lang:'Hari Bahasa Ibu', w:'Hari Perempuan',
    water:'Hari Air Sedunia', earth:'Hari Bumi', lab:'Hari Buruh', env:'Hari Lingkungan Hidup',
    ch:'Hari Anak', youth:'Hari Pemuda', peace:'Hari Perdamaian', teach:'Hari Guru',
    un:'Hari PBB', hr:'Hari Hak Asasi Manusia', xm:'Natal (Barat)', ev:'Malam Tahun Baru',
    ew:'Paskah (Barat)', eo:'Paskah (Ortodoks)', val:'Hari Valentine',
    father:'Hari Ayah', mother:'Hari Ibu', men:'Hari Pria Internasional', book:'Hari Buku Sedunia',
    health:'Hari Kesehatan Sedunia', space:'Hari Penerbangan Antariksa', music:'Hari Musik Internasional',
    disab:'Hari Penyandang Disabilitas', vol:'Hari Relawan', vdayE:'Hari Kemenangan (Timur)',
    vdayW:'Hari Kemenangan (Barat)', holocaust:'Hari Peringatan Holocaust', oceans:'Hari Laut Sedunia',
    elderly:'Hari Lansia Internasional', post:'Hari Pos Sedunia', tv:'Hari Televisi Sedunia',
    mountains:'Hari Gunung Internasional', migrants:'Hari Migran Internasional',
    peace2:'Hari Perdamaian dan Rekonsiliasi', diwali:'Diwali', holi:'Holi',
    eidF:'Idul Fitri', eidA:'Idul Adha'
  },
  tl:'Tema gelap', tn:'Tema terang', lb:'Bahasa'
};