export default {
  ttl: 'Calendario Fisso Internazionale',
  t_in: 'Data da convertire', t_yr: 'Anno intero',
  s1: 'Sol: giu–lug', s2: 'Sol: lug–ago',
  t_pk: 'Calendario', t_res: 'Risultato', t_hl: 'Festività internazionali dell\'anno',
  t_diff: 'Differenza tra date',
  cg:'Gregoriano', cj:'Giuliano', cc:'Cinese', ch:'Ebraico',
  ci:'Indù', cm:'Islamico', cp:'Persiano', ck:'Copto',
  go:'Converti', bad:'Questa data non esiste nel calendario scelto',
  badyear:'L\'anno deve essere compreso tra 1 e 9999', badseason:'Stagione 1–24, giorno 1–15',
  copy:'Copia', share:'Condividi', ics:'ICS',
  copied:'Copiato', copyFail:'Copia fallita', linkCopied:'Link copiato',
  icsDone:'File ICS scaricato',
  dDiff:'Totale', dDays:'giorni', dWeeks:'sett.', dYMD:'Calendario',
  dYears:'a.', dMonths:'mesi', dIFC:'Per CFI',
  m:['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
  mg:['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'],
  im:['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Sol','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
  img:['gennaio','febbraio','marzo','aprile','maggio','giugno','Sol','luglio','agosto','settembre','ottobre','novembre','dicembre'],
  wd:['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'],
  ws:['Do','Lu','Ma','Me','Gi','Ve','Sa'], pw:['Lu','Ma','Me','Gi','Ve','Sa','Do'],
  leap:'Giorno Bissextile', year:'Giorno dell\'Anno', noweek:'fuori settimana',
  gr:'Gregoriano', ju:'Giuliano', cn:'Cinese', hb:'Ebraico',
  in:'Indù', is:'Islamico', pe:'Persiano', co:'Copto',
  legend:'● — festività. Ogni mese inizia di domenica; passa il mouse su un giorno per vedere la data gregoriana.',
  note:'Tutte le date via JDN. Indù (Vikram Samvat) — modello semplificato. Islamico, Persiano, Copto — algoritmi tabellari.',
  hm:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadan','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  isml:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadan','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  pm:['Farwardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farwardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenale'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenale'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Capodanno', orx:'Natale (Ortodosso)', lang:'Giornata della Lingua Madre', w:'Festa della Donna',
    water:'Giornata Mondiale dell\'Acqua', earth:'Giornata della Terra', lab:'Festa del Lavoro', env:'Giornata dell\'Ambiente',
    ch:'Giornata dei Bambini', youth:'Giornata della Gioventù', peace:'Giornata della Pace', teach:'Giornata degli Insegnanti',
    un:'Giornata delle Nazioni Unite', hr:'Giornata dei Diritti Umani', xm:'Natale (Occidentale)', ev:'Vigilia di Capodanno',
    ew:'Pasqua (Occidentale)', eo:'Pasqua (Ortodossa)', val:'San Valentino',
    father:'Festa del Papà', mother:'Festa della Mamma', men:'Giornata Internazionale dell\'Uomo', book:'Giornata Mondiale del Libro',
    health:'Giornata Mondiale della Salute', space:'Giornata del Volo Spaziale Umano', music:'Giornata Internazionale della Musica',
    disab:'Giornata delle Persone con Disabilità', vol:'Giornata del Volontariato', vdayE:'Giorno della Vittoria (Est)',
    vdayW:'Giorno della Vittoria (Ovest)', holocaust:'Giorno della Memoria', oceans:'Giornata Mondiale degli Oceani',
    elderly:'Giornata Internazionale degli Anziani', post:'Giornata Mondiale della Posta', tv:'Giornata Mondiale della Televisione',
    mountains:'Giornata Internazionale della Montagna', migrants:'Giornata Internazionale dei Migranti',
    peace2:'Giornata della Pace e della Riconciliazione', diwali:'Diwali', holi:'Holi',
    eidF:'Eid al-Fitr', eidA:'Eid al-Adha'
  },
  tl:'Tema scuro', tn:'Tema chiaro', lb:'Lingua'
};