export default {
  ttl: 'Międzynarodowy Kalendarz Stały',
  t_in: 'Data do konwersji', t_yr: 'Cały rok',
  s1: 'Sol: cze–lip', s2: 'Sol: lip–sie',
  t_pk: 'Kalendarz', t_res: 'Wynik', t_hl: 'Międzynarodowe święta roku',
  t_diff: 'Różnica między datami',
  cg:'Gregoriański', cj:'Juliański', cc:'Chiński', ch:'Hebrajski', ci:'Hinduski', cm:'Islamski', cp:'Perski', ck:'Koptyjski',
  go:'Konwertuj', bad:'Ta data nie istnieje w wybranym kalendarzu', badyear:'Rok musi być między 1 a 9999', badseason:'Sezon 1–24, dzień 1–15',
  copy:'Kopiuj', share:'Udostępnij', ics:'ICS',
  copied:'Skopiowano', copyFail:'Nie udało się skopiować', linkCopied:'Skopiowano link', icsDone:'Pobrano ICS',
  dDiff:'Razem', dDays:'dni', dWeeks:'tyg.', dYMD:'Kalendarzowo', dYears:'l.', dMonths:'mies.', dIFC:'Wg MKS',
  m:['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
  mg:['stycznia','lutego','marca','kwietnia','maja','czerwca','lipca','sierpnia','września','października','listopada','grudnia'],
  im:['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Sol','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'],
  img:['stycznia','lutego','marca','kwietnia','maja','czerwca','Sol','lipca','sierpnia','września','października','listopada','grudnia'],
  wd:['niedziela','poniedziałek','wtorek','środa','czwartek','piątek','sobota'],
  ws:['Nd','Pn','Wt','Śr','Cz','Pt','Sb'], pw:['Pn','Wt','Śr','Cz','Pt','Sb','Nd'],
  leap:'Dzień Przestępny', year:'Dzień Roku', noweek:'poza tygodniem',
  gr:'Gregoriański', ju:'Juliański', cn:'Chiński', hb:'Hebrajski', in:'Hinduski', is:'Islamski', pe:'Perski', co:'Koptyjski',
  legend:'● — święto. Każdy miesiąc zaczyna się w niedzielę; najedź na dzień, aby zobaczyć datę gregoriańską.',
  note:'Wszystkie daty przez JDN. Hinduski (Vikram Samwat) — uproszczony model. Islamski, Perski, Koptyjski — algorytmy tabelaryczne.',
  hm:['Tiszri','Cheszwan','Kislew','Tewet','Szewat','Adar','Nisan','Ijar','Siwan','Tamuz','Aw','Elul','Adar II'],
  hml:['Tiszri','Cheszwan','Kislew','Tewet','Szewat','Adar','Nisan','Ijar','Siwan','Tamuz','Aw','Elul','Adar II'],
  im2:['Czajtra','Waiszaka','Dźjesztha','Aszadha','Szrawana','Bhadrapada','Aszwin','Kartika','Margaszirsza','Pausza','Magha','Phalguna'],
  iml:['Czajtra','Waiszaka','Dźjesztha','Aszadha','Szrawana','Bhadrapada','Aszwin','Kartika','Margaszirsza','Pausza','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabi al-awwal','Rabi as-sani','Dżumada al-ula','Dżumada as-sanija','Radżab','Szaban','Ramadan','Sziwwal','Zul-kada','Zul-hidżdża'],
  isml:['Muharram','Safar','Rabi al-awwal','Rabi as-sani','Dżumada al-ula','Dżumada as-sanija','Radżab','Szaban','Ramadan','Sziwwal','Zul-kada','Zul-hidżdża'],
  pm:['Farwardin','Ordibeheszt','Chordad','Tir','Mordad','Szahriwar','Mehr','Aban','Azar','Dej','Bahman','Esfand'],
  pml:['Farwardin','Ordibeheszt','Chordad','Tir','Mordad','Szahriwar','Mehr','Aban','Azar','Dej','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenalny'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenalny'],
  jq:['Liczun','Juszui','Jingdże','Czunfen','Cingming','Guju','Lisja','Sjaoman','Mangdżong','Sjadży','Sjaoszu','Daszu','Liciu','Czuszu','Bajlu','Czufen','Hanlu','Szuangdżiang','Lidong','Sjaoszie','Daszie','Dongdży','Sjaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Nowy Rok', orx:'Boże Narodzenie (prawosławne)', lang:'Dzień Języka Ojczystego', w:'Dzień Kobiet',
    water:'Światowy Dzień Wody', earth:'Dzień Ziemi', lab:'Święto Pracy', env:'Dzień Środowiska',
    ch:'Dzień Dziecka', youth:'Dzień Młodzieży', peace:'Dzień Pokoju', teach:'Dzień Nauczyciela',
    un:'Dzień ONZ', hr:'Dzień Praw Człowieka', xm:'Boże Narodzenie (katolickie)', ev:'Sylwester',
    ew:'Wielkanoc (zachodnia)', eo:'Wielkanoc (prawosławna)', val:'Walentynki',
    father:'Dzień Ojca', mother:'Dzień Matki', men:'Międzynarodowy Dzień Mężczyzn',
    book:'Światowy Dzień Książki', health:'Światowy Dzień Zdrowia', space:'Dzień Lotów Kosmicznych',
    music:'Dzień Muzyki', disab:'Dzień Osób Niepełnosprawnych', vol:'Dzień Wolontariusza',
    vdayE:'Dzień Zwycięstwa (Wschód)', vdayW:'Dzień Zwycięstwa (Zachód)',
    holocaust:'Dzień Pamięci o Holokauście', oceans:'Dzień Oceanów',
    elderly:'Dzień Osób Starszych', post:'Światowy Dzień Poczty', tv:'Światowy Dzień Telewizji',
    mountains:'Dzień Gór', migrants:'Dzień Migrantów',
    peace2:'Dzień Pokoju i Pojednania', diwali:'Diwali', holi:'Holi',
    eidF:'Id al-Fitr', eidA:'Id al-Adha'
  },
  tl:'Ciemny motyw', tn:'Jasny motyw', lb:'Język'
};