export default {
  ttl: 'Calendário Fixo Internacional',
  t_in: 'Data para converter', t_yr: 'Ano completo',
  s1: 'Sol: jun–jul', s2: 'Sol: jul–ago',
  t_pk: 'Calendário', t_res: 'Resultado', t_hl: 'Feriados internacionais do ano',
  t_diff: 'Diferença entre datas',
  cg:'Gregoriano', cj:'Juliano', cc:'Chinês', ch:'Hebraico',
  ci:'Hindu', cm:'Islâmico', cp:'Persa', ck:'Copta',
  go:'Converter', bad:'Esta data não existe no calendário escolhido',
  badyear:'O ano deve estar entre 1 e 9999', badseason:'Estação 1–24, dia 1–15',
  copy:'Copiar', share:'Compartilhar', ics:'ICS',
  copied:'Copiado', copyFail:'Falha ao copiar', linkCopied:'Link copiado',
  icsDone:'Arquivo ICS baixado',
  dDiff:'Total', dDays:'dias', dWeeks:'sem.', dYMD:'Calendário',
  dYears:'a.', dMonths:'m.', dIFC:'Por CFI',
  m:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
  mg:['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'],
  im:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Sol','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
  img:['janeiro','fevereiro','março','abril','maio','junho','Sol','julho','agosto','setembro','outubro','novembro','dezembro'],
  wd:['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'],
  ws:['Do','Se','Te','Qa','Qi','Se','Sá'], pw:['Se','Te','Qa','Qi','Se','Sá','Do'],
  leap:'Dia Bissexto', year:'Dia do Ano', noweek:'fora da semana',
  gr:'Gregoriano', ju:'Juliano', cn:'Chinês', hb:'Hebraico',
  in:'Hindu', is:'Islâmico', pe:'Persa', co:'Copta',
  legend:'● — feriado. Cada mês começa no domingo; passe o mouse sobre um dia para ver a data gregoriana.',
  note:'Todas as datas via JDN. Hindu (Vikram Samvat) — modelo simplificado. Islâmico, Persa, Copta — algoritmos tabulares.',
  hm:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tishrei','Cheshvan','Kislev','Tevet','Shevat','Adar','Nisan','Iyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  iml:['Chaitra','Vaisakha','Jyeshtha','Ashadha','Shravana','Bhadrapada','Ashvin','Kartika','Margashirsha','Pausha','Magha','Phalguna'],
  ism:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadã','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  isml:['Muharram','Safar','Rabi al-awwal','Rabi al-thani','Jumada al-ula','Jumada al-akhira','Rajab','Shaaban','Ramadã','Shawwal','Dhu al-Qadah','Dhu al-Hijjah'],
  pm:['Farwardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  pml:['Farwardin','Ordibehesht','Khordad','Tir','Mordad','Shahrivar','Mehr','Aban','Azar','Dey','Bahman','Esfand'],
  km:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  kml:['Thout','Paopi','Hathor','Koiak','Tobi','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Epagomenal'],
  jq:['Lichun','Yushui','Jingzhe','Chunfen','Qingming','Guyu','Lixia','Xiaoman','Mangzhong','Xiazhi','Xiaoshu','Dashu','Liqiu','Chushu','Bailu','Qiufen','Hanlu','Shuangjiang','Lidong','Xiaoxue','Daxue','Dongzhi','Xiaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],
  H: {
    ny:'Ano Novo', orx:'Natal (Ortodoxo)', lang:'Dia da Língua Materna', w:'Dia da Mulher',
    water:'Dia Mundial da Água', earth:'Dia da Terra', lab:'Dia do Trabalho', env:'Dia do Meio Ambiente',
    ch:'Dia das Crianças', youth:'Dia da Juventude', peace:'Dia da Paz', teach:'Dia do Professor',
    un:'Dia da ONU', hr:'Dia dos Direitos Humanos', xm:'Natal (Ocidental)', ev:'Véspera de Ano Novo',
    ew:'Páscoa (Ocidental)', eo:'Páscoa (Ortodoxa)', val:'Dia dos Namorados',
    father:'Dia dos Pais', mother:'Dia das Mães', men:'Dia Internacional do Homem', book:'Dia Mundial do Livro',
    health:'Dia Mundial da Saúde', space:'Dia do Voo Espacial Humano', music:'Dia Internacional da Música',
    disab:'Dia das Pessoas com Deficiência', vol:'Dia do Voluntário', vdayE:'Dia da Vitória (Leste)',
    vdayW:'Dia da Vitória (Oeste)', holocaust:'Dia da Memória do Holocausto', oceans:'Dia Mundial dos Oceanos',
    elderly:'Dia Internacional do Idoso', post:'Dia Mundial dos Correios', tv:'Dia Mundial da Televisão',
    mountains:'Dia Internacional das Montanhas', migrants:'Dia Internacional dos Migrantes',
    peace2:'Dia da Paz e Reconciliação', diwali:'Diwali', holi:'Holi',
    eidF:'Eid al-Fitr', eidA:'Eid al-Adha'
  },
  tl:'Tema escuro', tn:'Tema claro', lb:'Idioma'
};