export default {
  ttl: 'Uluslararası Sabit Takvim',
  t_in: 'Dönüştürülecek tarih', t_yr: 'Tam yıl',
  s1: 'Sol: Haz–Tem', s2: 'Sol: Tem–Ağu',
  t_pk: 'Takvim', t_res: 'Sonuç', t_hl: 'Yılın uluslararası tatilleri',
  t_diff: 'Tarihler arası fark',
  cg:'Miladi', cj:'Jülyen', cc:'Çin', ch:'İbrani', ci:'Hindu', cm:'İslami', cp:'Pers', ck:'Kıpti',
  go:'Dönüştür', bad:'Bu tarih seçilen takvimde yok', badyear:'Yıl 1 ile 9999 arasında olmalı', badseason:'Mevsim 1–24, gün 1–15',
  copy:'Kopyala', share:'Paylaş', ics:'ICS',
  copied:'Kopyalandı', copyFail:'Kopyalanamadı', linkCopied:'Bağlantı kopyalandı', icsDone:'ICS indirildi',
  dDiff:'Toplam', dDays:'gün', dWeeks:'hafta', dYMD:'Takvimsel', dYears:'y.', dMonths:'ay', dIFC:'MFS göre',
  m:['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],
  mg:['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],
  im:['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Sol','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],
  img:['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Sol','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'],
  wd:['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'],
  ws:['Pz','Pt','Sa','Ça','Pe','Cu','Ct'], pw:['Pt','Sa','Ça','Pe','Cu','Ct','Pz'],
  leap:'Artık Gün', year:'Yıl Günü', noweek:'hafta dışı',
  gr:'Miladi', ju:'Jülyen', cn:'Çin', hb:'İbrani', in:'Hindu', is:'İslami', pe:'Pers', co:'Kıpti',
  legend:'● — tatil. Her ay Pazar günü başlar; Miladi tarihi görmek için bir günün üzerine gelin.',
  note:'Tüm tarihler JDN üzerinden. Hindu (Vikram Samvat) — basitleştirilmiş model. İslami, Pers, Kıpti — tablo algoritmaları.',
  hm:['Tişri','Heşvan','Kislev','Tevet','Şevat','Adar','Nisan','İyar','Sivan','Tammuz','Av','Elul','Adar II'],
  hml:['Tişri','Heşvan','Kislev','Tevet','Şevat','Adar','Nisan','İyar','Sivan','Tammuz','Av','Elul','Adar II'],
  im2:['Çaytra','Vaişaka','Cyeştha','Aşadha','Şravana','Bhadrapada','Aşvin','Kartika','Margashirsha','Pauşa','Magha','Phalguna'],
  iml:['Çaytra','Vaişaka','Cyeştha','Aşadha','Şravana','Bhadrapada','Aşvin','Kartika','Margashirsha','Pauşa','Magha','Phalguna'],
  ism:['Muharrem','Safer','Rebiülevvel','Rebiülahir','Cemaziyelevvel','Cemaziyelahir','Recep','Şaban','Ramazan','Şevval','Zilkade','Zilhicce'],
  isml:['Muharrem','Safer','Rebiülevvel','Rebiülahir','Cemaziyelevvel','Cemaziyelahir','Recep','Şaban','Ramazan','Şevval','Zilkade','Zilhicce'],
  pm:['Ferverdin','Ordibeheşt','Hordad','Tir','Mordad','Şehriver','Mehr','Aban','Azar','Dey','Bahman','İsfend'],
  pml:['Ferverdin','Ordibeheşt','Hordad','Tir','Mordad','Şehriver','Mehr','Aban','Azar','Dey','Bahman','İsfend'],
  km:['Tout','Paopi','Hator','Koiak','Tobi','Meşir','Paremhat','Parmouti','Paşons','Paoni','Epip','Mesori','Epagomenal'],
  kml:['Tout','Paopi','Hator','Koiak','Tobi','Meşir','Paremhat','Parmouti','Paşons','Paoni','Epip','Mesori','Epagomenal'],
  jq:['Liçun','Yuşui','Jingje','Çunfen','Çingming','Guyu','Lisiya','Syaoman','Mangzhong','Syaçi','Syaoşu','Daşu','Liçiu','Çuşu','Bailu','Çiufen','Hanlu','Şuangjiang','Lidong','Syaoşue','Daşue','Dongçi','Syaohan','Dahan'],
  gan:['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],
  zhi:['Zi','Çou','Yin','Mao','Çen','Si','Wu','Vey','Şen','You','Şü','Hay'],
  H: {
    ny:'Yılbaşı', orx:'Noel (Ortodoks)', lang:'Ana Dil Günü', w:'Kadınlar Günü',
    water:'Dünya Su Günü', earth:'Dünya Günü', lab:'Emek Günü', env:'Çevre Günü',
    ch:'Çocuk Günü', youth:'Gençlik Günü', peace:'Barış Günü', teach:'Öğretmenler Günü',
    un:'BM Günü', hr:'İnsan Hakları Günü', xm:'Noel (Batı)', ev:'Yılbaşı Gecesi',
    ew:'Paskalya (Batı)', eo:'Paskalya (Ortodoks)', val:'Sevgililer Günü',
    father:'Babalar Günü', mother:'Anneler Günü', men:'Uluslararası Erkekler Günü',
    book:'Dünya Kitap Günü', health:'Dünya Sağlık Günü', space:'Uzay Uçuşu Günü',
    music:'Müzik Günü', disab:'Engelliler Günü', vol:'Gönüllüler Günü',
    vdayE:'Zafer Günü (Doğu)', vdayW:'Zafer Günü (Batı)',
    holocaust:'Holokost Anma Günü', oceans:'Dünya Okyanuslar Günü',
    elderly:'Yaşlılar Günü', post:'Dünya Posta Günü', tv:'Dünya Televizyon Günü',
    mountains:'Dağlar Günü', migrants:'Göçmenler Günü',
    peace2:'Barış ve Uzlaşma Günü', diwali:'Divali', holi:'Holi',
    eidF:'Ramazan Bayramı', eidA:'Kurban Bayramı'
  },
  tl:'Koyu tema', tn:'Açık tema', lb:'Dil'
};